# Generated by Django 4.2.6 on 2023-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('current_price', models.FloatField()),
                ('last_updated', models.DateTimeField()),
                ('change_percent', models.FloatField()),
            ],
        ),
    ]
