# Generated by Django 4.2.6 on 2023-11-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_percent',
            field=models.CharField(max_length=20),
        ),
    ]
