# Generated by Django 4.2.6 on 2023-12-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_portfoliostock_stockportfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stockportfolio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.stockportfolio'),
            preserve_default=False,
        ),
    ]
