# Generated by Django 4.2.6 on 2023-12-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_userprofile_stockportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stockportfolio',
        ),
    ]
